### ISSUE TITLE
Suggestion to stop cache issues

### ISSUE THREAD

**Issue by ricardovigatti** [igaster/laravel-theme#104]
Very often me or my colleagues run into problems because theme's configs are being cached. Takes some time until we remember to clear off the cache. I want know what you think about this update to config/themes.php file:

```php
// instead of 
'cache' => true,

// we do
'cache' => env('THEMES_CACHE', false),
```

**Comment by igaster** [comment]
I know that cache can be a problem because it will be forgotten.

So in my last commit, I defaulted it to false: https://github.com/igaster/laravel-theme/blob/master/src/Config/themes.php#L41

I agree with your solution, but I didn't want to create .env  entries. You can publish the config file and change it as you suggested...

**Comment by ricardovigatti** [comment]
Its ok, I was looking for an opinion about my approach. 😄 Thanks!
