### ISSUE TITLE
Wonderful theme manager! You don't even need to specify the theme to use! It just intuits it all!

### ISSUE THREAD

**Issue by LarryTX** [igaster/laravel-theme#105]
I love your package! According to your very own directions at https://github.com/igaster/laravel-theme/wiki/1.-Installation:
1. You install the package.
1. You optionally publish the configuration file. (Assuming you're on Laravel 5.5+) But why bother? Absolutely no need to specify anything. Put 50 different themes in your project. This package is so smart it will intuit which theme you want to use.
Then according to your own instructions, you're completely done. Just one problem. Put 50 different themes in your project? Where? What file structure? What are the required files? Oh yes, just how does Laravel inuit which theme to use?

Packages like this are what gives Laravel a bad name. It sends newcomers running away just as fast as they can.

Are you planning on publishing actual usage instructions for your package? If so, when? Why did't you create those instructions before you ever published your package. Other frameworks would never allow you to publish a completely unfinished product like this. (Oh yes, I forget, Laravel has no quality control. That's why you can do something like this mess.) Anyway, if you ever plan on finishing this package, please let me know. I might be interested.

**Comment by DeanWard** [comment]
The instructions clearly say where to place the themes: "you create a folder for each Theme in 'resources/views' and keep all your views separated"

Did you bother to read the rest of the instructions or just stop at the first page?

There is a whole page about setting themes.

https://github.com/igaster/laravel-theme/wiki/5.-Setting-the-active-theme

Maybe instead of bashing other people's work you should concentrate on learning to gather the information that is presented to you.

**Comment by igaster** [comment]
@LarryTX it's all in the documentation...

Hmm did you miss the TOC on the right column? Github wiki is not the best tool to create documentation (but it is better than putting all the docs into the repository). I wish I had time to build a proper website to host the documentation and some examples.... (Maybe I will....)

Again if you think that documentation is not well-structured please let me know. As the author of the package, I might take the wrong decisions about what a new user would expect to find here...

**Comment by JunaidQadirB** [comment]
Now I'm worried someone puts a link to one of the issues I opened but I don't care. This issue is a prime example of **How Not To Open An Issue**

If it were I, I would take a breath and express my concerns with more concerns and less taunts.

Anyways, I'm struggling with finding an example of how to use the theme in my controller.
