### ISSUE TITLE
use gulp or Elixir assets is a good idea

### ISSUE THREAD

**Issue by lichnow** [igaster/laravel-theme#24]
why not use gulp or elixir deal assets?it is a good solution

**Comment by igaster** [comment]
Gulp and Elixir are build systems that can be used in the pipeline when you are building your themes. Just configure them to ouput compiled assets to each theme's folder. I don't know how these could be part of the package since the aim of this package is different than these tools... maybe some build-in scripts to reduce configuration?

**Comment by gcphost** [comment]
I don't see any need to include gulp or elixir, it's not to difficult to get them setup as per what you said, for each theme.

The theme designer should be creating these themselves.
