### ISSUE TITLE
Namespace change

### ISSUE THREAD

**Issue by hailwood** [igaster/laravel-theme#37]
Hey @igaster,

What's your thoughts on updating the namespace to `Igaster\LaravelTheme` (case changes).
It's really odd having leading lowercase namespaces.

Thought I'd float the idea before I send through a pull request as it is technically a breaking change for something minor (I'm just kinda OCD ;)) so would require a major version bump.

The other option of course if we *really* wanted to avoid the major version bump but do want the updated namespace is to introduce a compatibility namespace - so everything in `igaster\laravelTheme` has mirror classes to `Igaster\LaravelTheme` but they are simply empty classes that extend the others e.g.

```php
<?php

namespace igaster\laravelTheme;

class Theme extends Igaster\LaravelTheme\Theme {}
````

which we would remove when we needed to bump the major version for any reason.

**Comment by igaster** [comment]
Hello @hailwood, You are absolutely right. Lowercase is a leftover from the first demos that I created localy... I've thought myself to change it but decided not to, because it is a minor flaw... 

Consdering the dual-namespace you proposed I'm afraid that it may cause more maintainance trouble in the future since it shoud be updated for every new feature until the next major version. I think that the best timing will be when a new major version occurs (which is quite possible in the near future given the number of Breaking Changes every new Laravel version introduces!)

Thank you for all your quality submitions!
