### ISSUE TITLE
theme_url() not working

### ISSUE THREAD

**Issue by jhourlad** [igaster/laravel-theme#61]
Call to undefined function theme_url()

**Comment by igaster** [comment]
theme_url() is registered into themeServiceProvider. So you may check that:

a) You have declared themeServiceProvider in config\app.php
b) You didn't try to call the aboce function before registering the Service provider (it is intented for use in Blade files)

This function is an alias to `\Theme::url()`. You may check if this is failing too...

If none of the above works please post your results in order to help me debug the error! Thank you for submitting!

**Comment by jhourlad** [comment]
I ended up using ``\Theme::url()`` instead. Haven't confirmed if the 2 suggestions work on my project but will do today.
