### ISSUE TITLE
All views not found.

### ISSUE THREAD

**Issue by MatthewSH** [igaster/laravel-theme#76]
I install the package, create a default theme, set the default theme, and move all the files from the default location to the themes location. I can move them back to the default views folder (configured in `config/view.php`) and it will work, and I can even change that to the theme path and it will work. 

It seems as though it's still running the default Laravel `FileViewFinder` and it's not registering the custom one. Currently using Laravel 5.5.19 and PHP 7.

**Comment by igaster** [comment]
Hello @MatthewSH, sorry for the delay...

I've just tested the package with your environment (Laravel 5.5.19, PHP7) and it works fine with me. It is strange that it doesn't register the ThemeViewFinder... I suspect that the order in the Service Providers array is wrong. Can you paste here the config/app.php file to inspect?

**Comment by mpenna** [comment]
I can confirm that this happens to me too. Laravel 5.4. Views were not found with corresponding logged error showing that it was being thrown by Laravel's FileViewFinder. Right now I'm no longer using the package but I'd very much like to.

**Comment by igaster** [comment]
I will check it on a fresh installation... Can you sent me a copy of your config/app.php file? You will find my email in my profile

**Comment by igaster** [comment]
Update: @MatthewSH @mpenna, I checked on a fresh L5.5 installation and it works fine. It is normal to have an exception thrown by `FileViewFinder` since this package extends it.. 

You may try the following steps to locate the error:
1. Run `artisan` command. If the package is installed correctly then you should see `theme` commands listed.
2. Run `artisan theme:list`. If your theme is registered correctly you should see your it listed. (Did you put it in the correct folder?)
3. Just before rendering your view insert `dd(\Theme::get());`. You should see that your theme has been enabled. (Have you set your active theme?)

**Comment by dimm** [comment]
Hello! I had same problem. But I solved it.
Only Need to set 'themes_path' => resource_path('views/themes') in config\themes.php.

Works for me!

**Comment by igaster** [comment]
@dimm thank you for your feedback. This entry in the configuration file is necessary if you choose to put your themes in a different folder than the root your `views` folder. (in your case you have moved them into a subfolder). You could also put them outside of your `views` folder, for example:

'themes_path' => resource_path('themes')
