### ISSUE TITLE
Laravel Mix

### ISSUE THREAD

**Issue by zietbukuel** [igaster/laravel-theme#77]
Hi, I'd like to know what's the best way to use [Laravel Mix](https://laravel.com/docs/5.5/mix) with this package. I'd really appreciate if you could help me out. Thanks.

**Comment by igaster** [comment]
Hello @zietbukuel! 

You are free to integrate your prefered workflow when developing frontend themes. Infact I am using Laravel Mix on my projects too... This is my setup:

1. I put my css/js etc of each theme on the same folder with my views (you can pick any location as long as they are not in the public folder. eg `resources/assets/ThemeName`)
2. I setup Laravel Mix to compile my files and  save the compiled files inside each Themes's asset folder (inside the public folder so that they can be served)
3. In my views I include the compiled js/css files (like any other asset).

As you can see Laravel Mix (Steps 1+2 = Development) doesn't interfere with the Package itself (Step 3 = Runtime)

This is an example of my webpack.js configuration:

```
// ThemeA assets
mix.js('resources/views/ThemeA/js/app.js', 'public/ThemeA/js')
  .sass('resources/views/ThemeA/sass/app.scss', 'public/ThemeA/css');

// ThemeB assets
mix.js('resources/views/ThemeB/js/app.js', 'public/ThemeB/js')
  .sass('resources/views/ThemeB/sass/app.scss', 'public/ThemeB/css');
```

**Comment by zietbukuel** [comment]
Thank you it works very nice this way.

**Comment by igaster** [comment]
Actually I included this into the documentation! It can be usefull to
someone else...

**Comment by sinamiandashti** [comment]
does it support versioning ?
use mix-manifest.json to determine file versions ?
there nothing in the documentation @igaster

**Comment by sinamiandashti** [comment]
`{!! Theme::js(mix(Theme::url('js/app.js')));  !!}`

fixed by this
but maybe its not a good solution

**Comment by igaster** [comment]
@sinamiandashti, there are some issues...

`mix()` will return the actuall path including the theme's path, and will not work with themes, so:
- If (a) You are not extending this theme OR (b) Your child them doesn't use it's own `app.js`, then you can skip `Theme::js()` and just use `mix()`
- if you want a child theme to use it's own `app.js` (redifining parent's theme file) then you can not use versioning... The url that you feed to `Theme:js()` must not contain the theme's path...

**Comment by ricardovigatti** [comment]
@sinamiandashti solution seems to be working. But I guess @igaster response might be discouraging us to use this approach. I wanna use both theme's inheritance and asset versioning. What should I do?

**Comment by z-h-z-h** [comment]
So why it's closed?
How we can use inheritance and versioning both?

**Comment by zietbukuel** [comment]
It's closed because the original question has been answered. If you want to address something else go open your own ticket and leave this alone, thanks.
