### ISSUE TITLE
Theme::set(''); doesn't work

### ISSUE THREAD

**Issue by stephenson-lms** [igaster/laravel-theme#87]
I created a controller to change the theme, but the Theme :: set ('my-theme') function does not work. The application does not return an error, but does not apply the theme.

My form
			<?php $themes = Theme::all(); foreach($themes as $theme){ ?>
								
```
<?php $themes = Theme::all(); foreach($themes as $theme){ ?>
  <div class="col-sm-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><?php echo $theme->name; ?></h5>

	<form method="post" action="<?php echo URL::route('style.change_theme'); ?>">
            <button class="btn btn-primary" type="submit">Ativar</button>
	    <input type="hidden" value="<?php echo $theme->name; ?>" name="theme">
	    <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
	</form>
      </div>
    </div>
  </div>
<?php } ?>
```
My route

`Route::post('/admin/style/change-theme', ['as'=>'style.change_theme', 'uses' => 'StyleController@changeTheme']);`

My controller

```
public function changeTheme(Request $request){
    $themeName = $request->theme;

    if(Theme::set($themeName)){
        return redirect()->back();
    } else{
        echo "Ocorreu um erro inesperado";
    }
}
```

**Comment by igaster** [comment]
This is strange...  Can you make some checks?
- Are you using the latest version of the package (2.0.6 currently). You can Run `composer show` to list all your packages.
- What is the value of `$request->theme`. Give an example...
- Can you try to `dd(Theme::current()` after you have set the theme? You should get a Theme instance
- Do you have some themes installed? Run `artisan theme:list` to gel the list of your themes. Try to set one of these

**Comment by igaster** [comment]
Maybe this part was not explained well in the docs. I made some updates, and also put this example so that other users can use it:

https://github.com/igaster/laravel-theme/wiki/5.-Setting-the-active-theme#example-let-the-user-change-the-theme

**Comment by stephenson-lms** [comment]
Thanks for answering. Let's go..
1 - I using the latest version (2.0.6).
2 - $request->theme is the theme name (look at the form on loop).
3 - If a change the controller for

```
public function changeTheme(Request $request){
    $themeName = $request->theme;
    \Theme::set($themeName);
     dd(\Theme::current());
}
```
return the correct theme, but when i go to theme switcher and run the same function dd(\Theme::current()); return the default theme (not change);

4 - When i run artisan theme:list everything seems to be correct

**Comment by igaster** [comment]
So you can set the theme sucessfully for this request. But where are you setting it for the subsequent requests? 

Try to follow the exaple with the session as a reference: https://github.com/igaster/laravel-theme/wiki/5.-Setting-the-active-theme#example-let-the-user-change-the-theme

**Comment by stephenson-lms** [comment]
I tried this solution, but it did not work ... Just to warn you have a little mistake in it, you forgot to close []
I'm trying to make a system to change the site theme, like WordPress

**Comment by kavin-90** [comment]
AppService Provider does not get any **session** because session start after all providers are loaded.

**Comment by JFossey** [comment]
So I was also having problems with theme switching.

After a lot of hair pulling I found my problem and I think it could be related to what is being experienced here.

The problem is that `FileViewFinder` keeps a cache of rendered views. So if you are switching between themes for example in a queue generating emails and the views paths are the same EG: `mytemplate.blade.php` but should resolve for one job to `mytheme.mytemplate` and another to `someothertheme.mytemplate`, the second job will get the rendered view from the first job.

**How to reproduce the problem**

_SETUP:_ Create two views of the same name but with different content in two different themes.

```php
// default theme = 'abc'
$resultAbc = View::make('my-email');
\Theme::set('xyz');
$resultXyz = View::make('my-email');
if ($resultAbc === $resultXyz) {
  throw \Exception('Wrong view')
}
```

**How to work around the problem by manually flushing the view cache**

```php
// default theme = 'abc'
$resultAbc = View::make('my-email');
\Theme::set('xyz');
\View::flushFinderCache();
$resultXyz = View::make('my-email');
if ($resultAbc === $resultXyz) {
  throw \Exception('Wrong view')
}
```

**A fix for me was to call flush() when `setPaths()` is called**

```php
    /**
     * Set the array of paths wherew the views are being searched.
     *
     * @param  array  $paths
     */
    public function setPaths($paths){
        $this->paths = $paths;
        $this->flush();
    }
```
**Suggested Long Term Fix**

The above is a quick fix, but long term fix would be to maybe keep track of cached views for each theme for performance. You could also argue that clearing the cache is the more correct way to go. If so we could make cached view tracking optional based on a config.

**Comment by igaster** [comment]
Thank you for your feedback... I will try to reproduce the issue..

Just be aware that if you have some workers running and make ANY changes on
the application, then you need to restart the workers in order to reload
the application and have the changes applied. Check
https://laravel.com/docs/5.5/queues#queue-workers-and-deployment

On the other hand is possible that Laravel will not recompile the views
when you are editing them. I have encountered this problem myself, but I
didn't have to recompile them on each request. This would hurt
performance... I will investigate further and let you know..

**Comment by JFossey** [comment]
@igaster 
Sorry, I dont think I was very clear, the view cash that is getting cleared / flushed in my example is not the same as when you run `artisan view:clear`. This is a more like a resolved paths view cache.

If you look at the [FileViewFinder::find()](https://github.com/laravel/framework/blob/5.6/src/Illuminate/View/FileViewFinder.php#L72) you will see that it keeps a cache of all resolved view paths.

If you look at the [FileViewFinder::flush()](https://github.com/laravel/framework/blob/5.6/src/Illuminate/View/FileViewFinder.php#L254) you will see that it flushes the _located views cache_.

So when `Themes::set()` is called and you set the [paths](https://github.com/igaster/laravel-theme/blob/322d743e3161bb88c23b0f6da9820ec5e3e46e6d/src/Themes.php#L77) you need to also flush the views located views cache, else any view of the same name will return the previous themes path.

I hope that makes more sense.
